# Generated by Django 3.2.8 on 2021-12-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_date_de_publication_articles_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='images',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
