# Generated by Django 4.0 on 2021-12-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
